# Версия приложения
APP_VERSION_CODE=7089
APP_VERSION_NAME=12.10.3
APP_PACKAGE=com.neacheer.messenger
IS_PRIVATE=false

# Keystore
RELEASE_KEY_PASSWORD=qwe123
RELEASE_KEY_ALIAS=ngram
RELEASE_STORE_PASSWORD=qwe123

# Память и производительность
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configureondemand=false

# Android
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.enableR8.fullMode=true
android.r8.optimizedResourceShrinking=true
android.enableResourceOptimizations=true

org.gradle.tooling.parallel=true